### ISSUE TITLE
Silos on Models.py

### ISSUE THREAD

**Issue by mgutierrezc** [Leeps-Lab/random_number_game#3]
Hi @alkngo, what does this block do? Is silos a subgroup within an otree group?
https://github.com/Leeps-Lab/random_number_game/blob/25af0af3f90d93533c66fd381412e8e3d3c8291c/models.py#L53-L71

**Comment by alkngo** [comment]
Hello,

Silos is another mechanism used to assign groups. It won't be needed in a regular oTree project, so you can ignore it. Also, the actual groups in the game will have to be manually made so that it is 2 males + 2 females, because I don't think oTree has a way to assign groups based on player attributes like gender.
